steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/revie-backend-image:$COMMIT_SHA", "."]

  # 2. Push the Docker image to Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/revie-backend-image:$COMMIT_SHA"]

  # 3. Deploy the new image to Cloud Run
  - name: "gcr.io/google.com/cloudsdk/cloud-sdk"
    args: [
        "gcloud",
        "run",
        "deploy",
        "revie-backend",
        "--image",
        "gcr.io/$PROJECT_ID/revie-backend-image:$COMMIT_SHA",
        "--region",
        "europe-west9",
        "--platform",
        "managed",
        # "--min-instances",
        # "1",
        # "--set-env-vars",
        # "TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN},SUPABASE_URL=${_SUPABASE_URL},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}",
      ]
    env:
      - "CLOUDSDK_CORE_DISABLE_PROMPTS=1"
options:
  logging: CLOUD_LOGGING_ONLY
